apiVersion: v1
kind: Secret
metadata:
  name: dns-secret
type: Opaque
data:
  cloudflare_api_token: {{ .Values.secrets.cloudflare | b64enc }}
  cloudflare-api-token: {{ .Values.secrets.cloudflare | b64enc }}
  pihole-ext: {{ .Values.secrets.piholeExt | b64enc }}
  pihole: {{ .Values.secrets.pihole | b64enc }}
  pihole1: {{ .Values.secrets.pihole1 | b64enc }}
