apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delugevpn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn
  volumeName: delugevpn-pv
