apiVersion: v1
kind: Service
metadata:
  name: {{ include "delugevpn.fullname" . }}
  labels:
    {{- include "delugevpn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: privoxy
      port: 8118
      protocol: TCP
      targetPort: 8118
    - name: vpn-port
      port: 58846
      protocol: TCP
      targetPort: 58846
    - name: additional-vpn-port
      port: 58946
      protocol: TCP
      targetPort: 58946
  selector:
    {{- include "delugevpn.selectorLabels" . | nindent 4 }}
