repositories:
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: dns-secrets
    chart: ./charts/dns-secrets
    namespace: dns
    values:
      - ./charts/dns-secrets/values.yaml

  - name: ingress-nginx-internal
    chart: ingress-nginx/ingress-nginx
    namespace: nginx-system
    values:
      - ./charts/ingress-nginx-internal/values.yaml

  - name: ingress-nginx-external
    chart: ingress-nginx/ingress-nginx
    namespace: nginx-system
    values:
      - ./charts/ingress-nginx-external/values.yaml

  - name: pihole
    chart: mojo2600/pihole
    namespace: dns
    values:
      - ./charts/pihole/values.yaml

  - name: external-dns-pihole1
    chart: bitnami/external-dns
    namespace: dns
    values:
      - ./charts/external-dns/dns1.yaml

  - name: external-dns-pihole3
    chart: bitnami/external-dns
    namespace: dns
    values:
      - ./charts/external-dns/dns3.yaml

  - name: external-dns-cloudflare
    chart: bitnami/external-dns
    namespace: dns
    values:
      - ./charts/external-dns/cloudflare.yaml

  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: dns
    wait: true
    values:
      - ./charts/cert-manager/values.yaml
    hooks:
    - events: ["presync"]
      showlogs: true
      command: "./charts/cert-manager/cert-manager-crd.sh"
      args:
      - "upgrade"
      - v1.17.1
    - events: ["postsync"]
      showlogs: true
      command: "/bin/sleep"
      args: ["15"]
    - events: ["postuninstall"]
      showlogs: true
      command: "./charts/cert-manager/cert-manager-crd"
      args:
      - "uninstall"
      - v1.17.1

  - name: cert-manager-issuers
    needs: ['dns/cert-manager']
    chart: ./charts/cert-manager-issuers
    namespace: dns
    values:
      - ./charts/cert-manager-issuers/values.yaml
