repositories:
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  # - name: pihole
  #   chart: mojo2600/pihole
  #   namespace: dns
  #   version: 2.28.0
  #   values:
  #     - ./charts/pihole/values.yaml
  - name: dns-secrets
    chart: ./charts/dns-secrets
    namespace: dns
    values:
      - ./charts/dns-secrets/values.yaml

  - name: ingress-nginx-internal
    chart: ingress-nginx/ingress-nginx
    namespace: nginx-system
    version: 4.12.0
    values:
      - ./charts/nginx-internal/values.yaml

  - name: external-dns1
    chart: bitnami/external-dns
    namespace: dns
    version: 8.8.3
    values:
      - ./charts/external-dns/dns1.yaml

  - name: external-dns2
    chart: bitnami/external-dns
    namespace: dns
    version: 8.7.7
    values:
      - ./charts/external-dns/dns2.yaml

  # Ignoring until pihole v6 fixes the API
  # - name: external-dns3
  #   chart: bitnami/external-dns
  #   namespace: dns-system
  #   version: 8.7.6
  #   values:
  #     - ./charts/external-dns/dns3.yaml

  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: dns
    version: 1.17.1
    wait: true
    values:
      - ./charts/cert-manager/values.yaml
    hooks:
    - events: ["presync"]
      showlogs: true
      command: "./charts/cert-manager/cert-manager-crd.sh"
      args:
      - "upgrade"
      - v1.17.1
    - events: ["postsync"]
      showlogs: true
      command: "/bin/sleep"
      args: ["15"]
    - events: ["postuninstall"]
      showlogs: true
      command: "./charts/cert-manager/cert-manager-crd"
      args:
      - "uninstall"
      - v1.17.1

  - name: cert-manager-issuers
    needs: ['dns/cert-manager']
    chart: ./charts/cert-manager-issuers
    namespace: dns
    values:
      - ./charts/cert-manager-issuers/values.yaml
