repositories:
  - name: jameswynn
    url: https://jameswynn.github.io/helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: nicholaswilde
    url: https://nicholaswilde.github.io/helm-charts
  - name: stirling-pdf
    url: https://stirling-tools.github.io/Stirling-PDF-chart
  - name: pascaliske
    url: https://charts.pascaliske.dev
  - name: gabe565
    url: https://charts.gabe565.com
---
releases:
  - name: default-secrets
    chart: ./charts/default-secrets
    values:
      - ./charts/default-secrets/values.yaml

  - name: default-ingress
    chart: ./charts/default-ingress
    values:
      - ./charts/default-ingress/values.yaml

  - name: servus-player
    chart: ./charts/servus-player
    values:
      - ./charts/servus-player/values.yaml
      - ./charts/servus-player/image.yaml

  - name: servus-extapi
    chart: ./charts/servus-extapi
    values:
      - ./charts/servus-extapi/values.yaml
      - ./charts/servus-extapi/image.yaml

  - name: servus-prices
    chart: ./charts/servus-prices
    values:
      - ./charts/servus-prices/values.yaml
      - ./charts/servus-prices/image.yaml

  - name: servus-boardgames
    chart: ./charts/servus-boardgames
    values:
      - ./charts/servus-boardgames/values.yaml
      - ./charts/servus-boardgames/image.yaml

  - name: homepage
    chart: jameswynn/homepage
    values:
      - ./charts/homepage/values.yaml

  - name: stirling-pdf
    chart: stirling-pdf/stirling-pdf-chart
    values:
      - ./charts/stirling-pdf/values.yaml

  - name: minio
    chart: bitnami/minio
    version: 17.0.3
    values:
      - ./charts/minio/values.yaml

  - name: linkding
    chart: pascaliske/linkding
    values:
      - ./charts/linkding/values.yaml

  - name: servus-admin
    chart: ./charts/servus-admin
    values:
      - ./charts/servus-admin/values.yaml

  - name: ladder
    chart: ./charts/ladder
    values:
      - ./charts/ladder/values.yaml

  - name: picoshare
    chart: ./charts/picoshare
    values:
      - ./charts/picoshare/values.yaml
