config:
  settingsString: |
    layout:
      Media:
        style: row
        columns: 4
      Applications:
        style: row
        columns: 4
      Tech:
        style: row
        columns: 4
      Developer:

  services:
    - Media:
      - Plex:
          icon: plex.svg
          href: https://plex.dictummortuum.com/web/index.html#!/media/a46300ed136b86cef11b73b12817e6bd4fc04a71/com.plexapp.plugins.library?source=2
          description: Streaming

    - Applications:
      - Nextcloud:
          icon: nextcloud.svg
          href: https://nextcloud.dictummortuum.com
          description: Files
      - Synology:
          icon: synology.svg
          href: https://synology.dictummortuum.com
          description: NAS
      - Admin:
          icon: google-admin.svg
          href: https://admin.dictummortuum.com
          description: Admin panel
      - Admin2:
          icon: google-admin.svg
          href: https://admin2.dictummortuum.com
          description: Admin panel
      - Brother:
          icon: brother.svg
          href: http://typographus.dictummortuum.com/general/status.html
          description: Printer

    - Tech:
      - Pihole1:
          icon: pi-hole.svg
          href: https://dns.dictummortuum.com
          description: DNS
      - Pihole2:
          icon: pi-hole.svg
          href: https://dns2.dictummortuum.com
          description: DNS
      - Ubiquiti:
          icon: ubiquiti.svg
          href: https://router.dictummortuum.com
          description: Router
      - phpMyAdmin:
          icon: phpmyadmin.svg
          href: https://db.dictummortuum.com
          description: Database
      - phpLDAPAdmin:
          icon: phpldapadmin.png
          href: https://satellite.dictummortuum.com/phpldapadmin/
          description: LDAP
      - Gitea:
          icon: gitea.svg
          href: https://git.dictummortuum.com/
          description: Git server
      - Portainer:
          icon: portainer.svg
          href: http://sol.dictummortuum.com:9000/
          description: Docker manager
      - Cyberchef:
          icon: cyberchef.svg
          href: https://cyberchef.dictummortuum.com/
          description: Swiss Army Knife

  bookmarks:
    - Social:
      - Facebook:
          - abbr: FB
            href: https://www.facebook.com/
      - Messenger:
          - abbr: MSG
            href: https://www.messenger.com/
      - Github:
          - abbr: GH
            href: https://www.github.com/
      - Discord:
          - abbr: DSC
            href: https://www.discord.com/app
      - Slack:
          - abbr: SLK
            href: https://app.slack.com/
      - Boardgamegeek:
          - abbr: BGG
            href: https://boardgamegeek.com/
      - HackerNews:
          - abbr: HN
            href: https://news.ycombinator.com/
      - Gmail:
          - abbr: GM
            href: https://gmail.com/
      - Youtube:
          - abbr: YT
            href: https://www.youtube.com/
      - Eurobank:
          - abbr: EUB
            href: https://ebanking.eurobank.gr/

  widgets: {}
    # - kubernetes:
    #     cluster:
    #       show: true
    #       cpu: true
    #       memory: true
    #       showLabel: true
    #       label: "cluster"
    #     nodes:
    #       show: true
    #       cpu: true
    #       memory: true
    #       showLabel: true
  kubernetes:
    mode: default

env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "dash.dictummortuum.com"

serviceAccount:
  create: true
  name: homepage

enableRbac: true

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - secretName: homepage-tls
        hosts:
          - "dash.dictummortuum.com"
    hosts:
      - host: dash.dictummortuum.com
        paths:
          - path: /
            pathType: ImplementationSpecific
