replicaCount: 1

image:
  repository: binhex/arch-delugevpn
  pullPolicy: IfNotPresent
  tag: "2.1.1-8-03"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}

securityContext:
  privileged: true
  sysctls:
    - name: net.ipv4.conf.all.src_valid_mark
      value: "1"
  # capabilities:
  #   add:
  #     - NET_ADMIN

env:
  PUID: "1986"
  PGID: "1986"
  VPN_PROV: pia
  VPN_ENABLED: true
  VPN_CLIENT: wireguard
  LAN_NETWORK: 10.96.0.0/12,192.168.1.0/24,10.244.0.0/16
  VPN_INPUT_PORTS: 1234
  VPN_OUTPUT_PORTS: 5678

service:
  type: ClusterIP
  port: 8112

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - secretName: deluge-tls
      hosts:
        - deluge.dictummortuum.com
  hosts:
    - host: deluge.dictummortuum.com
      paths:
        - path: /
          pathType: ImplementationSpecific

secrets:
  username: ref+sops://secrets.yaml#/pia/username
  password: ref+sops://secrets.yaml#/pia/password

resources: {}

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# livenessProbe:
#   httpGet:
#     path: /
#     port: http
# readinessProbe:
#   httpGet:
#     path: /
#     port: http

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - name: vpn-deployment-volume
    persistentVolumeClaim:
      claimName: delugevpn-pvc

volumeMounts:
  - mountPath: /data
    name: vpn-deployment-volume
    subPath: data
  - mountPath: /config
    subPath: config
    name: vpn-deployment-volume
  - mountPath: /config/wireguard/
    subPath: config/wireguard/
    name: vpn-deployment-volume

nodeSelector: {}

tolerations: []

affinity: {}
