apiVersion: v1
kind: ConfigMap
metadata:
  name: autoindex-config
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;
            server_name _;

            root /data;
            index index.html;

            autoindex on;                # enable directory listing
            autoindex_exact_size off;    # human-readable sizes
            autoindex_localtime on;      # show localtime for files
        }
    }
