apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-archivebox
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-static
  volumeName: pv-nfs-archivebox