apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-archivebox
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  mountOptions:
    - vers={{ .Values.nfs.vers }}
  nfs:
    server: {{ .Values.nfs.server }}
    path: /volume1/archivebox
