persistentVolumeClaim:
  enabled: true

serviceWeb:
  loadBalancerIP: 192.168.1.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 192.168.1.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: DNS
    gethomepage.dev/group: Tech
    gethomepage.dev/icon: pi-hole
    gethomepage.dev/name: Pihole3
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=pihole"
  tls:
  - hosts:
      - dns3.dictummortuum.com
    secretName: pihole-tls
  hosts:
  - "dns3.dictummortuum.com"

doh:
  enabled: true
  pullPolicy: Always
  envVars: {
    DOH_UPSTREAM: "https://1.1.1.1/dns-query"
  }

monitoring:
  podMonitor:
    enabled: true
  sidecar:
    enabled: true
