provider: pihole
policy: upsert-only
txtOwnerId: "homelab"

pihole:
  server: https://dns3.dictummortuum.com
extraEnvVars:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: dns-secret
        key: pihole-ext

serviceAccount:
  create: false
  name: "external-dns"

ingressClassFilters:
  - nginx-internal
