provider: pihole
policy: upsert-only
registry: noop

pihole:
  server: https://dns3.dictummortuum.com
extraEnvVars:
  - name: EXTERNAL_DNS_PIHOLE_API_VERSION
    value: "6"
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: dns-secret
        key: pihole-ext

ingressClassFilters:
  - nginx-internal

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

# logLevel: debug
