apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: prowlarr-pv
