linkding:
  enabled: true
  name: linkding
  className: nginx-internal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Link management
    gethomepage.dev/group: Applications
    gethomepage.dev/icon: linkding
    gethomepage.dev/name: Linkding
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=linkding"
  tls:
    - secretName: linkding-tls
      hosts:
        - "linkding.dictummortuum.com"
  hosts:
    - host: linkding.dictummortuum.com
      paths:
        - path: /
          pathType: ImplementationSpecific
          backendService: linkding
          backendPort: 9090

navidrome:
  enabled: true
  name: navidrome
  className: nginx-internal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Music
    gethomepage.dev/group: Media
    gethomepage.dev/icon: navidrome
    gethomepage.dev/name: Navidrome
    gethomepage.dev/pod-selector: ""
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Remote-User admin;
  tls:
    - secretName: music-tls
      hosts:
        - "music.dictummortuum.com"
  hosts:
    - host: music.dictummortuum.com
      paths:
        - path: /
          pathType: ImplementationSpecific
          backendService: synology
          backendPort: 4533
