ingress:
  enabled: true
  className: nginx-internal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: default-ingress-tls
      hosts:
        - "linkding.dictummortuum.com"
  hosts:
    - host: linkding.dictummortuum.com
      paths:
        - path: /
          pathType: ImplementationSpecific
          backendService: linkding
          backendPort: 9090
