apiVersion: v1
kind: Secret
metadata:
  name: extapi-secrets
type: Opaque
data:
  apiflash_host: {{ .Values.secrets.apiflash.host | b64enc }}
  apiflash_key: {{ .Values.secrets.apiflash.key | b64enc }}
  minio_host: {{ .Values.secrets.minio.host | b64enc }}
  minio_key: {{ .Values.secrets.minio.key | b64enc }}
  minio_secret: {{ .Values.secrets.minio.secret| b64enc }}
