on:
  # push:
  #   paths:
  #     'cmd/database-exporter/**.go'
  workflow_dispatch: {}

jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "package database-exporter"
    environment: default
    steps:
    - uses: passeidireto/trigger-external-workflow-action@main
      env:
        PAYLOAD_REPO: "database-exporter"
        PAYLOAD_ARCH: "aarch64"
      with:
        repository: DictumMortuum/pacman
        event: package
        github_pat: ${{ secrets.PAT }}
