on: [push, workflow_dispatch]
jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "📦 Trigger Project Test"
    environment: default
    steps:
    - uses: passeidireto/trigger-external-workflow-action@main
      env:
        PAYLOAD_REPO: "servus-player"
        PAYLOAD_ARCH: "aarch64"
      with:
        repository: DictumMortuum/pacman
        event: package
        github_pat: ${{ secrets.PAT }}
    - uses: passeidireto/trigger-external-workflow-action@main
      env:
        PAYLOAD_REPO: "servus-extapi"
        PAYLOAD_ARCH: "aarch64"
      with:
        repository: DictumMortuum/pacman
        event: package
        github_pat: ${{ secrets.PAT }}
