on: [push, workflow_dispatch]
jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "📦 Trigger Project Test"
    steps:
    - uses: passeidireto/trigger-external-workflow-action@main
      env:
        PAYLOAD_AUTHOR: ${{ github.author }}
        PAYLOAD_REVISION: "3"
        PAYLOAD_REPO: "servus-player"
        PAYLOAD_ARCH: "aarch64"
      with:
        repository: DictumMortuum/pacman
        event: package
        github_pat: ${{ secrets.PAT }}
