on:
  # push:
  #   paths:
  #     'cmd/servus-prices/**.go'
  workflow_dispatch: {}

jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "package servus-prices"
    environment: default
    steps:
    - uses: passeidireto/trigger-external-workflow-action@main
      env:
        PAYLOAD_REPO: "servus-prices"
        PAYLOAD_ARCH: "aarch64"
      with:
        repository: DictumMortuum/pacman
        event: package
        github_pat: ${{ secrets.PAT }}
