on:
  push:
    paths:
      'cmd/servus-auth/**.go'
  workflow_dispatch: {}

jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "package servus-auth"
    environment: default
    steps:
    - uses: passeidireto/trigger-external-workflow-action@main
      env:
        PAYLOAD_REPO: "servus-auth"
        PAYLOAD_ARCH: "aarch64"
      with:
        repository: DictumMortuum/pacman
        event: package
        github_pat: ${{ secrets.PAT }}
