apiVersion: apps/v1
kind: Deployment
metadata:
  name: rod
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rod
  template:
    metadata:
      labels:
        app: rod
    spec:
      containers:
        - name: rod
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 7317
