replicaCount: 1
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}

env:
  GIN_MODE: release
securityContext: {}

service:
  type: ClusterIP
  port: 10003

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: servus-prices-tls
      hosts:
        - "api.dictummortuum.com"
        - "extapi.dictummortuum.com"
  hosts:
    - host: api.dictummortuum.com
      paths:
        - path: /prices
          pathType: ImplementationSpecific
    - host: extapi.dictummortuum.com
      paths:
        - path: /prices
          pathType: ImplementationSpecific

resources: {}

livenessProbe:
  httpGet:
    path: /prices/version
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /prices/version
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumeMounts:
  - mountPath: /etc/conf.d/
    name: servus-conf

volumes:
  - name: servus-conf
    secret:
      secretName: servusrc
      items:
        - key: servus-conf
          path: servusrc.yml

nodeSelector: {}
tolerations: []
affinity: {}
---
